repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml

  - repo: "https://github.com/gitleaks/gitleaks"
    rev: "v8.24.2"
    hooks:
      - id: gitleaks

  - repo: local
    hooks:
      - id: cargo-fmt
        name: "cargo fmt"
        entry: "cargo fmt --all --check"
        language: "system"
        types: ["rust"]
        pass_filenames: false

      - id: cargo-nextest
        name: "cargo nextest"
        # Remove exports below if you don't have these tools installed
        entry: bash -c "
          export RUSTC_WRAPPER=kache &&
          export RUSTC_LINKER=clang &&
          export CARGO_BUILD_RUSTFLAGS="-C link-arg=-fuse-ld=mold" &&
          cargo test --doc &&
          cargo nextest run -j1
          "
        language: "system"
        types: ["rust"]
        pass_filenames: false

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        # Optional: Add --fix to automatically correct format violations
        args: ["--fix"]
