name: Rust

permissions:
  contents: read

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test all
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v7

    - name: Cache Rust dependencies
      uses: Swatinem/rust-cache@v2

    - name: Install nextest
      uses: taiki-e/install-action@nextest

    - name: Run all tests
      run: |
          cargo nextest run -j1 --no-fail-fast

  test-matrix:
    name: Test ${{ matrix.platform.os-name }}
    runs-on: ${{ matrix.platform.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        protocols: [http1, http2, http3]
        platform:
          - os-name: FreeBSD-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-freebsd
            skip-tests: true
          - os-name: Linux-x86_64
            runs-on: ubuntu-24.04
            target: x86_64-unknown-linux-musl
          - os-name: Linux-aarch64
            runs-on: ubuntu-24.04
            target: aarch64-unknown-linux-musl
          - os-name: Linux-arm
            runs-on: ubuntu-24.04
            target: arm-unknown-linux-musleabi
          - os-name: Linux-i686
            runs-on: ubuntu-24.04
            target: i686-unknown-linux-musl
            skip-tests: true
          #- os-name: Linux-powerpc
          #  runs-on: ubuntu-24.04
          #  target: powerpc-unknown-linux-gnu
          #  skip-tests: true
          - os-name: Linux-powerpc64
            runs-on: ubuntu-24.04
            target: powerpc64-unknown-linux-gnu
            skip-tests: true
          - os-name: Linux-powerpc64le
            runs-on: ubuntu-24.04
            target: powerpc64le-unknown-linux-gnu
            skip-tests: true
          - os-name: Linux-riscv64
            runs-on: ubuntu-24.04
            target: riscv64gc-unknown-linux-gnu
          - os-name: Linux-s390x
            runs-on: ubuntu-24.04
            target: s390x-unknown-linux-gnu
            skip-tests: true
          #- os-name: NetBSD-x86_64
          #  runs-on: ubuntu-24.04
          #  target: x86_64-unknown-netbsd
          #  skip-tests: true
          #  cross-version: 588b3c99db52b5a9c5906fab96cfadcf1bde7863
          - os-name: Windows-aarch64
            runs-on: windows-latest
            target: aarch64-pc-windows-msvc
            skip-tests: true
          - os-name: Windows-i686
            runs-on: windows-latest
            target: i686-pc-windows-msvc
            skip-tests: true
          - os-name: Windows-x86_64
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc
          - os-name: macOS-x86_64
            runs-on: macOS-latest
            target: x86_64-apple-darwin
          - os-name: macOS-aarch64
            runs-on: macOS-latest
            target: aarch64-apple-darwin
        toolchain:
          - stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Maybe install SSL packages
        run: sudo apt-get update --yes && sudo apt-get install --yes pkg-config openssl libssl-dev binutils
        if: matrix.platform.runs-on == 'ubuntu-24.04'

      - name: Build ${{ matrix.platform.target }} binary for vetis-tokio and ${{ matrix.protocols }} with rust-tls features
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args:
            "--package vetis-tokio --locked --release --features \"${{ matrix.protocols }} rust-tls deboa-tokio/${{ matrix.protocols }} deboa-tokio/rust-tls deboa-tokio/default-rustls-provider deboa-tokio/default-rustls-verifier\" --no-default-features"
          strip: true
          cross-version: ${{ matrix.platform.cross-version || 'v0.2.5' }}
          
      - name: Run tests for ${{ matrix.platform.target }} with vetis-tokio and ${{ matrix.protocols }} and rust-tls features
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "test"
          target: ${{ matrix.platform.target }}
          toolchain: ${{ matrix.toolchain }}
          args:
            "--package vetis-tokio --locked --release --features \"${{ matrix.protocols }} rust-tls deboa-tokio/${{ matrix.protocols }} deboa-tokio/rust-tls deboa-tokio/default-rustls-provider deboa-tokio/default-rustls-verifier\" --no-default-features"
        if: ${{ !matrix.platform.skip-tests }}
